import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from './context/CartContext'
import { GoogleAnalytics } from '././components/GoogleAnalytics'
import { TrackingProvider } from './components/TrackingProvider'
import { Suspense } from "react";

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Suspense>
        <CartProvider>
          <TrackingProvider>
            {children}
          </TrackingProvider>
        </CartProvider>
        <GoogleAnalytics />
        </Suspense>
      </body>
    </html>
  )
}
